version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          name: Restore cache (frontEnd)
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: 
          name: Deployment
          command: npm install
      
      - run:
          name: check eslint
          command: npm run eslint

      - save_cache:
          name: Saving cache (backend)
          paths:
            - src/server/node_modules
            - /home/circleci/.cache
            - /home/circleci/.npm
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Print the Current Time
          command: date
